Add Multiplex signal support. Fix big endian decoding.
bit-dream/candied pull request #46
Opened 2023-01-25 19:37 UTC by agent6262

Fix for #44 and #13. However this change is not fully featured as when adding and removing signals to the dbc they do not properly reflect in the object (also writing the db might not show multiplexing correctly?)

2023-01-25 19:39 UTC, agent6262 commented
@bit-dream as in my pr comment I was not able to completely finish adding proper multiplex support. Would definitely need help on dbc adding / removing and dbc writing.

2023-01-28 20:01 UTC, bit-dream requested changes
Hey, sorry for getting back to you late on this.

Overall, the changes look great. However, I think there are still some issues with the decode implementation, I don't think it's quite there yet/accurately decodes signals. I tried to be as detailed as I could with the comments, so check those out and let me know what you think.

That said, I would be willing to merge all of your changes into main, except for the changes to Can and BitUtils. If you want to want to open up a separate pull request for those other changes, I'll get those added, as I like what you did there.

As for the signal decoding logic, we may just need to revisit that. If you want me to take a stab at it I am happy too. If you want to take that on, you are welcome to as well.

2023-01-28 20:12 UTC, bit-dream commented
> @bit-dream as in my pr comment I was not able to completely finish adding proper multiplex support. Would definitely need help on dbc adding / removing and dbc writing.

That shouldn't be an issue at all. I can work on adding that functionality.

2023-01-31 01:59 UTC, agent6262 commented on src/can/BitUtils.ts
> +  static bigEndianBitOrder = [
I wont even attempt to claim to properly understand how can and candfd bit ordering stuff works. I am unable to find good documentation on it, so I was just attempting solutions till it got what I expected.

But as far as can fd goes I not super worried about it right now, as this lib does not account for it yet, but when that feature is added checks and function will need to change for it.

2023-01-31 02:01 UTC, agent6262 commented
@bit-dream I removed the can and bit changes as requested.

2023-01-31 02:19 UTC, bit-dream approved these changes

2023-01-31 02:20 UTC, merged

2023-01-31 02:23 UTC, bit-dream commented
@agent6262 I approved your pull request and merged into main. Awesome work and thanks for contributing.

I'll take a stab at implementing a more robust decode method. I'll update issue #45 so you can be in the loop when those changes get pulled in.

Additionally, if you are looking to be an active maintainer, feel free to give me a shout.